import 'package:cloud_firestore/cloud_firestore.dart';
import 'lib/config/firebase_init.dart';

Future<void> main() async {
  await FirebaseInit.initialize();
  
  print('Setting up SSU student clubs and societies...');
  
  try {
    final clubsRef = FirebaseFirestore.instance.collection('clubs');
    
    // Check if clubs already exist
    final existingClubs = await clubsRef.limit(1).get();
    if (existingClubs.docs.isNotEmpty) {
      print('Clubs already exist in database');
      return;
    }

    // Create SSU student clubs and societies based on actual website
    final ssuClubs = [
      {
        'name': 'I.T. Society',
        'description': 'A community for Information Technology students to share knowledge, collaborate on projects, and stay updated with the latest tech trends.',
        'type': 'technical',
        'status': 'active',
        'visibility': 'department',
        'department': 'cot',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Technology', 'Information Technology', 'Programming', 'Digital Innovation'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/system.png',
      },
      {
        'name': 'Society of English Majors',
        'description': 'Fostering excellence in English language, literature, and communication skills through academic and cultural activities.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['English', 'Literature', 'Communication', 'Language Arts'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/eng.png',
      },
      {
        'name': 'Mathematics Society',
        'description': 'Promoting mathematical excellence, problem-solving skills, and analytical thinking through workshops and competitions.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Mathematics', 'Problem Solving', 'Analytics', 'STEM'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/math.png',
      },
      {
        'name': 'Psychology Society',
        'description': 'Exploring human behavior, mental health awareness, and psychological research through seminars and community outreach.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Psychology', 'Mental Health', 'Human Behavior', 'Research'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/pschy.png',
      },
      {
        'name': 'Elementary Education Society',
        'description': 'Preparing future educators through teaching workshops, child development studies, and community service projects.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'coe',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Education', 'Elementary Teaching', 'Child Development', 'Community Service'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/elem.png',
      },
      {
        'name': 'Educators Society',
        'description': 'Professional development for education students through teaching methodologies, classroom management, and educational leadership.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'coe',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Education', 'Teaching', 'Professional Development', 'Leadership'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/educators.png',
      },
      {
        'name': 'Delta Engineering Society',
        'description': 'Advancing engineering excellence through technical projects, innovation workshops, and industry collaboration.',
        'type': 'technical',
        'status': 'active',
        'visibility': 'department',
        'department': 'coeng',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Engineering', 'Technical Innovation', 'Projects', 'Industry'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/delta.png',
      },
      {
        'name': 'KAUPOD (Kapisanan ng mga Mag-aaral sa Agrikultura)',
        'description': 'Promoting agricultural excellence, sustainable farming practices, and rural development through hands-on projects.',
        'type': 'academic',
        'status': 'active',
        'visibility': 'department',
        'department': 'coa',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Agriculture', 'Sustainable Farming', 'Rural Development', 'Environmental'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/kaupod.png',
      },
      {
        'name': 'United Student Council',
        'description': 'Representing student interests, organizing campus events, and fostering student leadership and governance.',
        'type': 'leadership',
        'status': 'active',
        'visibility': 'public',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Student Government', 'Leadership', 'Campus Events', 'Advocacy'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/united.png',
      },
      {
        'name': 'Red Cross Youth',
        'description': 'Promoting humanitarian service, disaster preparedness, and community health through volunteer activities.',
        'type': 'service',
        'status': 'active',
        'visibility': 'public',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Humanitarian', 'Disaster Preparedness', 'Community Service', 'Health'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/redcross.png',
      },
      {
        'name': 'Campus Ministry',
        'description': 'Fostering spiritual growth, religious activities, and interfaith dialogue within the university community.',
        'type': 'religious',
        'status': 'active',
        'visibility': 'public',
        'department': 'cas',
        'campus': 'main',
        'createdBy': 'admin',
        'createdAt': Timestamp.now(),
        'updatedAt': Timestamp.now(),
        'tags': ['Spiritual', 'Religious Activities', 'Interfaith', 'Community'],
        'memberIds': [],
        'moderatorIds': [],
        'adminIds': [],
        'settings': {},
        'requiresApproval': true,
        'isPublicContentApproved': true,
        'memberCount': 0,
        'eventCount': 0,
        'announcementCount': 0,
        'logoUrl': 'assets/images/clubs/ministry.png',
      },
    ];

    // Add clubs to Firestore
    for (final clubData in ssuClubs) {
      await clubsRef.add(clubData);
    }

    print('Successfully created ${ssuClubs.length} SSU student clubs and societies!');
  } catch (e) {
    print('Error creating SSU clubs: $e');
  }
} 